# Tweepy API
CONSUMER_KEY_TT = 'YOUR_CONSUMER_KEY_OF_TWITTER'
CONSUMER_SECRET_TT = 'YOUR_CONSUMER_SECRET_KEY_OF_TWITTER'
ACCESS_TOKEN_TT = 'YOUR_TOKEN_OF_TWITTER'
ACCESS_TOKEN_SECRET_TT = 'YOUR_SECRET_TOKEN_OF_TWITTER'

# MapQuest API
CONSUMER_KEY_MQ = 'YOUR_CONSUMER_KEY_OF_MAP_QUEST'
CONSUMER_SECRET_MQ = 'YOUR_CONSUMER_SECRET_KEY_OF_MAPQUEST'
BASE_URL = 'http://www.mapquestapi.com/directions/v2/optimizedroute?key=ZbNLwtP5iqAHJ4WcTcGvFQSjhkNmFLbJ&json='

# Spotipy API
SPOTIPY_CLIENT_ID = 'YOUR_CLIENT_KEY_OF_SPOTIPY'
SPOTIPY_CLIENT_SECRET = 'YOUR_CLIENT_SECRET_KEY_OF_SPOTIPY'
